header:
    title: 안녕하세요!
    text: iOS Developer
    button: Tell Me More
    buttonlink: "#services"

services:
    title: "Skills"
    text: "Lorem ipsum"
    section: services
    list:
      - title: "Language/Framwork"
        desc: "Objective-C, Java, Javascript, JSP, HTML, Spring"
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Web Server"
        desc: "Apache, Node,js, Tomcat, WebLogic"
        icon: fas fa-laptop       
      - title: "Database"
        desc: "Oracle, MySQL, SQLite"
        icon: fab fa-markdown

portfolio:
    title: "Projects"
    text: "아래 이미지를 클릭하면 상세 내용을 확인할 수 있습니다."
    section: portfolio
    closebutton: "Close Project"
    

timeline:
    title: "Career" 
    text: "경력사항입니다."
    section: timeline
    events:
      - title: "디비밸리(주) 입사"
        year: "2015-"
        desc: "개발2본부 / 모바일팀 / iOS 개발"
        image: assets/img/timeline/1.jpg
        alt: 
        align: left
        end: "끝날때까지 끝난게아니다."

about:
    title: "About Us"
    text: "our story"
    section: about

    
team:
    title: "Contact"
    text: "아래의 방법으로 연락해주세요."
    section: team
    people:
      - name: "E-Mail"
        role: "bell4912@naver.com"
      - name: "Phone"
        role: "010.939.7822"
        
                
# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
